#!/usr/bin/env bash
#
# Copyright (C) 2021 @alanndz (Telegram and Github)
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Kernel sCript Builder (kcb)
# Script Build kernel for vayu or Poco X3 Pro
# Credit to: Rama Bondan Prakoso (rama982)
#

export TZ=":Asia/Makassar"
conf="$HOME/.kcb"

function usage() {
echo -n "Author: alanndz
Usage: $(basename "$0") [OPTIONS] [COMMAND]

Options:
 -c | --clean     : Full clean
 -d | --dirty     : Dirty clean
 -n | --codename  <Codename>
 -C | --directory <Directory>
 -D | --defconfig <Defconfig>
 -j | --jobs      <Jobs number>
 -e | --env       <Env>
 -t | --telegram  <Chat id> <telegram bot>
 -r | --regen     : Regenerate configs
 -l | --lto       : Build using full LTO
 -h | --help      : Show usage
"
exit
}

function _conf() {
    mkdir -p $conf
    echo "$(openssl enc -base64 <<< ${1})" > $conf/.chat_id
    echo "$(openssl enc -base64 <<< ${2})" > $conf/.token
    exit
}

while (( ${#} )); do
  case ${1} in
       "-c"|"--clean") CLEAN=true ;;
       "-d"|"--dirty") DIRTY=true ;;
       "-n"|"--codename") shift; CODENAME="-${1}" ;;
       "-C"|"--directory") shift; DIR=${1} ;;
       "-D"|"--defconfig") shift; CONFIG=${1} ;;
       "-j"|"--jobs") shift; JOBS=${1} ;;
       "-e"|"--env") shift; ENV=${1} ;;
       "-r"|"--regen") REGEN=true ;;
       "-t"|"--telegram") shift; _conf ${1} ${2}; shift;;
       "-l"|"--lto") LTO=true ;;
       "-h"|"--help") usage ;;
  esac
  shift
done

if [[ -n ${DIR} ]]; then
  cd ${DIR}
fi
if [[ ! -f Makefile ]]; then
  echo "This not in rootdir kernel, please check directory again"
  exit 1
fi

# Setup environment
KDIR=$(pwd)
TC="${HOME}/.kcb-tools"
AK=${TC}/AnyKernel
KERNEL_NAME="aLn"
KERNEL_TYPE="EAS"
PHONE="Poco X3 Pro"
DEVICE="vayu"
CONFIG=${CONFIG:-vayu_defconfig}
CODENAME=${CODENAME:--Testing}
JOBS=${JOBS:-$(nproc --all)}
CHAT_ID="$(openssl enc -base64 -d <<< `cat $conf/.chat_id`)"
TOKEN="$(openssl enc -base64 -d <<< `cat $conf/.token`)"
DEVELOPER="alanndz"
HOST="noob_vayu-dev"
AK_BRANCH="vayu"

if [[ ! -d $TC/gcc64 || ! -d $TC/gcc32 ||  ! -d $AK ]]; then
    # git clone https://gitlab.com/alanndz/clang-aosp $TC/clang --depth=1 --no-tags --single-branch
    # git clone https://android.googlesource.com/platform/prebuilts/gas/linux-x86/ -b master $TC/gcc --depth=1 --single-branch --no-tags
    git clone https://github.com/arter97/arm64-gcc --depth=1 $TC/gcc64
    git clone https://github.com/arter97/arm32-gcc --depth=1 $TC/gcc32
    git clone https://github.com/alanndz/AnyKernel3 -b $AK_BRANCH ${AK}
fi

function sendInfo() {
    if [[ ! -n $CHAT_ID || ! -n $TOKEN ]]; then return; fi
    curl -s -X POST https://api.telegram.org/bot$TOKEN/sendMessage -d chat_id=$CHAT_ID -d "parse_mode=HTML" -d text="$(
            for POST in "${@}"; do
                echo "${POST}"
            done
        )"
&>/dev/null
}

function push() {
    if [[ ! -n $CHAT_ID || ! -n $TOKEN ]]; then return; fi
    curl -F document=@"$1" "https://api.telegram.org/bot$TOKEN/sendDocument" \
		-F chat_id="$CHAT_ID" \
		-F "disable_web_page_preview=true" \
		-F "parse_mode=html" \
		-F caption="Build took $(($DIFF / 60)) minute(s) and $(($DIFF % 60)) second(s). | #aLn | <b>vayu</b>"
}

# Setup name
GIT="$(git log --pretty=format:'%h' -1)"
ENDZ="${GIT}-$(date "+%d%m%Y-%H%M")"
KVERSION="${CODENAME}-${GIT}"
ZIP_NAME="${KERNEL_NAME}${CODENAME}-${DEVICE}-${ENDZ}.zip"
LOG=$(echo ${ZIP_NAME} | sed "s/.zip/.log/")
LOGE=$(echo ${ZIP_NAME} | sed "s/.zip/.error.log/")

# Setup clang environment
IMG="$KDIR/out/arch/arm64/boot/Image"
DTBO="$KDIR/out/arch/arm64/boot/dtbo.img"
DTB="$KDIR/out/arch/arm64/boot/dts/qcom"
CL="$TC/gcc64"
export PATH="${TC}/gcc64/bin:${TC}/gcc32/bin:$PATH"
# export LD_LIBRARY_PATH="${CL}/lib:$LD_LIBRARY_PATH"
KBUILD_COMPILER_STRING=$(${TC}/gcc64/bin/aarch64*-elf-gcc --version | head -n 1)
GCC64=$(ls ${TC}/gcc64/bin/aarch64*-gcc | sed 's/gcc$//')
GCC32=$(ls ${TC}/gcc32/bin/arm*-gcc | sed 's/gcc$//')

START=$(date +"%s")

disable_lto() {
  scripts/config --file out/.config -e CONFIG_THINLTO
}

enable_dtbo() {
  scripts/config --file out/.config -e CONFIG_BUILD_ARM64_DTBO_IMG
}

disable_auto_localv() {
  scripts/config --file out/.config -d CONFIG_LOCALVERSION_AUTO
}

xcache() {
  export CCACHE_EXEC=$(which ccache)
  export USE_CCACHE=1
  export CCACHE_DIR=$KDIR/.ccache
  ccache -M 20G >/dev/null
  # ccache -o compression=true
}

xcache

m() {
  make -j${JOBS} O=out \
                        ARCH=arm64 \
                        LOCALVERSION=${KVERSION} \
                        CROSS_COMPILE="${GCC64}" \
                        CROSS_COMPILE_ARM32="${GCC32}" \
                        CROSS_COMPILE_COMPAT="${GCC32}" \
                        ${ENV} \
                        ${@}
}

if [[ -n ${REGEN} ]]; then
  m $CONFIG
  #m menuconfig
  nano out/.config
  m savedefconfig
  cp out/defconfig arch/arm64/configs/$CONFIG
  exit 0
fi

if [[ -n ${CLEAN} ]]; then
  m mrproper 2>/dev/null
  m clean 2>/dev/null
fi

# Build kernel
rm -rf ${IMG}
rm -rf ${DTBO}

m $CONFIG > /dev/null
if [[ ! -n $LTO ]]; then disable_lto; fi
enable_dtbo
disable_auto_localv
m > >(tee out/${LOG}) 2> >(tee out/${LOGE} >&2)

END=$(date +"%s")
DIFF=$(($END - $START))

sendInfo "<b>----- ${KERNEL_NAME} New Kernel -----</b>" \
	"<b>Device:</b> ${DEVICE} or ${PHONE}" \
	"<b>Name:</b> <code>${KERNEL_NAME}${KVERSION}</code>" \
	"<b>Kernel Version:</b> <code>$(make kernelversion)</code>" \
	"<b>Type:</b> <code>${KERNEL_TYPE}</code>" \
	"<b>Branch:</b> <code>$(git branch --show-current)</code>" \
	"<b>Commit:</b> <code>$(git log --pretty=format:'%h : %s' -1)</code>" \
	"<b>Started on:</b> <code>$(hostname)</code>" \
	"<b>Compiler:</b> <code>${KBUILD_COMPILER_STRING}</code>"

if [[ ! -f ${IMG} ]]; then
  echo "Failed build!"
  push out/${LOG}
  push out/${LOGE}
  exit 1
fi

make -C ${AK} clean
cp ${IMG} ${AK}
cp ${DTBO} ${AK}
find ${DTB} -name "*.dtb" -exec cat {} + > ${AK}/dtb
make -C ${AK} ZIP="${ZIP_NAME}" normal

push ${AK}/${ZIP_NAME}
push out/${LOG}
